# Generated by Django 2.2 on 2021-07-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='state',
            field=models.IntegerField(choices=[(0, '正常'), (1, '温度异常'), (2, '湿度异常'), (3, '两个异常')], default=0, verbose_name='状态：状态(后台根据温湿度数据分别判断并返回值，0正常，1温度异常，2湿度异常, 3两个异常)'),
        ),
    ]
