# Generated by Django 2.2 on 2021-07-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environs', '0002_auto_20210709_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(verbose_name='时间戳')),
                ('temperature', models.CharField(max_length=10, verbose_name='温度')),
                ('humidity', models.CharField(max_length=10, verbose_name='湿度')),
                ('state', models.IntegerField(choices=[(0, '正常'), (1, '温度异常'), (2, '湿度异常'), (3, '两个异常')], default=0, max_length=2, verbose_name='状态：状态(后台根据温湿度数据分别判断并返回值，0正常，1温度异常，2湿度异常, 3两个异常)')),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
