# Generated by Django 2.2 on 2021-07-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=10, verbose_name='设备ID')),
                ('device_type', models.CharField(max_length=10, verbose_name='设备类型')),
                ('device_situation', models.CharField(max_length=255, verbose_name='设备在线情况')),
            ],
        ),
    ]
