# Generated by Django 2.2 on 2021-07-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=10, verbose_name='设备ID')),
                ('device_type', models.IntegerField(verbose_name='设备类型')),
                ('device_situation', models.BooleanField(default=True, verbose_name='设备工作状态')),
            ],
        ),
        migrations.CreateModel(
            name='devices_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type_id', models.IntegerField(verbose_name='设备类型')),
                ('device_name', models.CharField(max_length=100, verbose_name='设备类型文字描述')),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
