# Generated by Django 2.2 on 2021-07-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20210710_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices_model',
            old_name='device_type_id',
            new_name='device_type',
        ),
    ]
