# Generated by Django 2.2 on 2021-07-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210708_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='finger',
            field=models.ImageField(default=1, upload_to='', verbose_name='指纹信息'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='telephone',
            field=models.CharField(default=2, max_length=13, verbose_name='电话'),
            preserve_default=False,
        ),
    ]
