# Generated by Django 2.2 on 2021-07-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210709_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='finger',
            field=models.CharField(max_length=50, verbose_name='指纹信息'),
        ),
    ]
