# Generated by Django 2.2 on 2021-07-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='log_ip',
            field=models.CharField(default=123, max_length=20, verbose_name='访问ip'),
            preserve_default=False,
        ),
    ]
