# Generated by Django 2.2 on 2021-07-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(verbose_name='时间戳')),
                ('entry_person_id', models.CharField(max_length=10, verbose_name='人员id')),
                ('entry_person_name', models.CharField(max_length=10, verbose_name='人员姓名')),
            ],
        ),
    ]
