# Generated by Django 2.2 on 2021-07-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entryperson', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='entry_person',
        ),
    ]
